# Generated by Django 5.0 on 2024-01-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_alter_hero_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
